services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://lul:8080/auth
    ports:
      - 8080:8080
